// <auto-generated />
using System;
using DemoSaga.ProductService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoSaga.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20261004180639_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoSaga.ProductService.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4bc897b3-cc6f-471a-9610-5174a792cbe2"),
                            BasePrice = 1000m,
                            Name = "Product 1",
                            Quantity = 100
                        },
                        new
                        {
                            Id = new Guid("4a19d49a-4500-48ca-889a-ddf40fda4a5b"),
                            BasePrice = 200m,
                            Name = "Product 2",
                            Quantity = 200
                        },
                        new
                        {
                            Id = new Guid("6144efba-4775-4a06-8809-15504cd2adee"),
                            BasePrice = 700m,
                            Name = "Product 3",
                            Quantity = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
